// <auto-generated />
using System;
using HybridWash.Repositories.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HybridWash.Repositories.Migrations
{
    [DbContext(typeof(AutowashContext))]
    [Migration("20260814032207_TestMigration")]
    partial class TestMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HybridWash.Entities.Models.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BookingID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<DateTime?>("ActualWashTime")
                        .HasColumnType("datetime");

                    b.Property<DateOnly>("BookingDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("CustomerID");

                    b.Property<decimal?>("FinalPrice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("GuestLicensePlate")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("GuestName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GuestPhone")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("GuestVehicleType")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("IncidentImage1")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("IncidentImage2")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("OriginalPrice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.Property<int?>("PromotionId")
                        .HasColumnType("int")
                        .HasColumnName("PromotionID");

                    b.Property<string>("QrCode")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int")
                        .HasColumnName("ServiceID");

                    b.Property<int>("SlotId")
                        .HasColumnType("int")
                        .HasColumnName("SlotID");

                    b.Property<int?>("StaffId")
                        .HasColumnType("int")
                        .HasColumnName("StaffID");

                    b.Property<string>("StaffNote")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<int?>("VehicleId")
                        .HasColumnType("int")
                        .HasColumnName("VehicleID");

                    b.HasKey("BookingId")
                        .HasName("PK__Bookings__73951ACD7262D128");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PromotionId");

                    b.HasIndex("QrCode")
                        .IsUnique()
                        .HasFilter("[QrCode] IS NOT NULL");

                    b.HasIndex("ServiceId");

                    b.HasIndex("SlotId");

                    b.HasIndex("StaffId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("HybridWash.Entities.Models.BookingAddOn", b =>
                {
                    b.Property<int>("BookingAddOnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BookingAddOnID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingAddOnId"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int")
                        .HasColumnName("BookingID");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal>("FinalPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("OriginalPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int?>("PromotionId")
                        .HasColumnType("int")
                        .HasColumnName("PromotionID");

                    b.Property<int?>("RedemptionId")
                        .HasColumnType("int")
                        .HasColumnName("RedemptionID");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int")
                        .HasColumnName("ServiceID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Pending");

                    b.HasKey("BookingAddOnId");

                    b.HasIndex(new[] { "BookingId" }, "IX_BookingAddOns_BookingID");

                    b.HasIndex(new[] { "PromotionId" }, "IX_BookingAddOns_PromotionID");

                    b.HasIndex(new[] { "ServiceId" }, "IX_BookingAddOns_ServiceID");

                    b.HasIndex(new[] { "RedemptionId" }, "UX_BookingAddOns_RedemptionID")
                        .IsUnique()
                        .HasFilter("[RedemptionID] IS NOT NULL");

                    b.ToTable("BookingAddOns");
                });

            modelBuilder.Entity("HybridWash.Entities.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CustomerID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("CurrentPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("CurrentTier")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Member");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<decimal?>("TotalSpent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0m);

                    b.HasKey("CustomerId")
                        .HasName("PK__Customer__A4AE64B80ED0B1AD");

                    b.HasIndex(new[] { "PhoneNumber" }, "UQ__Customer__85FB4E3872752CA2")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("HybridWash.Entities.Models.ParkingReceipt", b =>
                {
                    b.Property<int>("ReceiptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ReceiptID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReceiptId"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int")
                        .HasColumnName("BookingID");

                    b.Property<string>("CustomerSignature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsCustomerLeaving")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("IssueStaffId")
                        .HasColumnType("int")
                        .HasColumnName("IssueStaffID");

                    b.Property<DateTime?>("IssuedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Issued");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("VerifyStaffId")
                        .HasColumnType("int")
                        .HasColumnName("VerifyStaffID");

                    b.HasKey("ReceiptId")
                        .HasName("PK__ParkingR__CC08C4009D92C04D");

                    b.HasIndex("IssueStaffId");

                    b.HasIndex("VerifyStaffId");

                    b.HasIndex(new[] { "BookingId" }, "UQ__ParkingR__73951ACC51E1CEE8")
                        .IsUnique();

                    b.ToTable("ParkingReceipts");
                });

            modelBuilder.Entity("HybridWash.Entities.Models.PointLedger", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TransactionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<int?>("BookingId")
                        .HasColumnType("int")
                        .HasColumnName("BookingID");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("CustomerID");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ExpireDate")
                        .HasColumnType("datetime");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<int?>("RewardRedemptionId")
                        .HasColumnType("int")
                        .HasColumnName("RewardRedemptionID");

                    b.Property<string>("TransactionType")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("TransactionId")
                        .HasName("PK__PointLed__55433A4B69BABF45");

                    b.HasIndex("BookingId");

                    b.HasIndex("CustomerId");

                    b.HasIndex(new[] { "RewardRedemptionId" }, "UX_PointLedger_RewardRedemptionID")
                        .IsUnique()
                        .HasFilter("([RewardRedemptionID] IS NOT NULL)");

                    b.ToTable("PointLedger", (string)null);
                });

            modelBuilder.Entity("HybridWash.Entities.Models.Promotion", b =>
                {
                    b.Property<int>("PromotionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PromotionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PromotionId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DiscountType")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal?>("DiscountValue")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal?>("MaxDiscount")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("PromoCode")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PromoName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PromoType")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("int")
                        .HasColumnName("ServiceID");

                    b.Property<string>("TargetTier")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("ValidFrom")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("datetime");

                    b.HasKey("PromotionId")
                        .HasName("PK__Promotio__52C42F2F7D471371");

                    b.HasIndex("ServiceId");

                    b.HasIndex(new[] { "PromoCode" }, "UQ__Promotio__32DBED350150C25C")
                        .IsUnique()
                        .HasFilter("[PromoCode] IS NOT NULL");

                    b.ToTable("Promotions");
                });

            modelBuilder.Entity("HybridWash.Entities.Models.Reward", b =>
                {
                    b.Property<int>("RewardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RewardID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RewardId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("DiscountValue")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("MinimumTier")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Member");

                    b.Property<int>("PointCost")
                        .HasColumnType("int");

                    b.Property<string>("RewardName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RewardType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("ServiceId")
                        .HasColumnType("int")
                        .HasColumnName("ServiceID");

                    b.Property<DateTime?>("ValidFrom")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("datetime");

                    b.HasKey("RewardId");

                    b.HasIndex(new[] { "ServiceId" }, "IX_Rewards_ServiceID");

                    b.HasIndex(new[] { "RewardName" }, "UQ_Rewards_RewardName")
                        .IsUnique();

                    b.ToTable("Rewards");
                });

            modelBuilder.Entity("HybridWash.Entities.Models.RewardRedemption", b =>
                {
                    b.Property<int>("RedemptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RedemptionID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RedemptionId"));

                    b.Property<int?>("BookingId")
                        .HasColumnType("int")
                        .HasColumnName("BookingID");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("CustomerID");

                    b.Property<int>("PointsSpent")
                        .HasColumnType("int");

                    b.Property<DateTime>("RedeemedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RewardId")
                        .HasColumnType("int")
                        .HasColumnName("RewardID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Issued");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("datetime");

                    b.HasKey("RedemptionId");

                    b.HasIndex(new[] { "BookingId" }, "IX_RewardRedemptions_BookingID");

                    b.HasIndex(new[] { "CustomerId" }, "IX_RewardRedemptions_CustomerID");

                    b.HasIndex(new[] { "RewardId" }, "IX_RewardRedemptions_RewardID");

                    b.HasIndex(new[] { "RequestId" }, "UQ_RewardRedemptions_RequestId")
                        .IsUnique();

                    b.ToTable("RewardRedemptions");
                });

            modelBuilder.Entity("HybridWash.Entities.Models.Service", b =>
                {
                    b.Property<int>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ServiceID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ServiceId")
                        .HasName("PK__Services__C51BB0EA6F4EB55B");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("HybridWash.Entities.Models.Staff", b =>
                {
                    b.Property<int>("StaffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("StaffID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StaffId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Role")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("Staff");

                    b.HasKey("StaffId")
                        .HasName("PK__Staff__96D4AAF775894E90");

                    b.HasIndex(new[] { "PhoneNumber" }, "UQ__Staff__85FB4E385B409A45")
                        .IsUnique();

                    b.ToTable("Staff");
                });

            modelBuilder.Entity("HybridWash.Entities.Models.TimeSlot", b =>
                {
                    b.Property<int>("SlotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SlotID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SlotId"));

                    b.Property<int>("BikeCapacity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(5);

                    b.Property<int>("CarCapacity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(2);

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("SlotId")
                        .HasName("PK__TimeSlot__0A124A4FD1897255");

                    b.ToTable("TimeSlots");
                });

            modelBuilder.Entity("HybridWash.Entities.Models.Vehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("VehicleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("CustomerID");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("VehicleType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("VehicleId")
                        .HasName("PK__Vehicles__476B54B2CEE7BEC8");

                    b.HasIndex("CustomerId");

                    b.HasIndex(new[] { "LicensePlate" }, "UQ__Vehicles__026BC15C3EEB94D8")
                        .IsUnique();

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("HybridWash.Entities.Models.Booking", b =>
                {
                    b.HasOne("HybridWash.Entities.Models.Customer", "Customer")
                        .WithMany("Bookings")
                        .HasForeignKey("CustomerId")
                        .HasConstraintName("FK__Bookings__Custom__5DCAEF64");

                    b.HasOne("HybridWash.Entities.Models.Promotion", "Promotion")
                        .WithMany("Bookings")
                        .HasForeignKey("PromotionId")
                        .HasConstraintName("FK__Bookings__Promot__60A75C0F");

                    b.HasOne("HybridWash.Entities.Models.Service", "Service")
                        .WithMany("Bookings")
                        .HasForeignKey("ServiceId")
                        .IsRequired()
                        .HasConstraintName("FK__Bookings__Servic__5FB337D6");

                    b.HasOne("HybridWash.Entities.Models.TimeSlot", "Slot")
                        .WithMany("Bookings")
                        .HasForeignKey("SlotId")
                        .IsRequired()
                        .HasConstraintName("FK__Bookings__SlotID__619B8048");

                    b.HasOne("HybridWash.Entities.Models.Staff", "Staff")
                        .WithMany("Bookings")
                        .HasForeignKey("StaffId")
                        .HasConstraintName("FK__Bookings__StaffI__628FA481");

                    b.HasOne("HybridWash.Entities.Models.Vehicle", "Vehicle")
                        .WithMany("Bookings")
                        .HasForeignKey("VehicleId")
                        .HasConstraintName("FK__Bookings__Vehicl__5EBF139D");

                    b.Navigation("Customer");

                    b.Navigation("Promotion");

                    b.Navigation("Service");

                    b.Navigation("Slot");

                    b.Navigation("Staff");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("HybridWash.Entities.Models.BookingAddOn", b =>
                {
                    b.HasOne("HybridWash.Entities.Models.Booking", "Booking")
                        .WithMany("BookingAddOns")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_BookingAddOns_Bookings");

                    b.HasOne("HybridWash.Entities.Models.Promotion", "Promotion")
                        .WithMany("BookingAddOns")
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_BookingAddOns_Promotions");

                    b.HasOne("HybridWash.Entities.Models.RewardRedemption", "Redemption")
                        .WithOne("BookingAddOn")
                        .HasForeignKey("HybridWash.Entities.Models.BookingAddOn", "RedemptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_BookingAddOns_RewardRedemptions");

                    b.HasOne("HybridWash.Entities.Models.Service", "Service")
                        .WithMany("BookingAddOns")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_BookingAddOns_Services");

                    b.Navigation("Booking");

                    b.Navigation("Promotion");

                    b.Navigation("Redemption");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("HybridWash.Entities.Models.ParkingReceipt", b =>
                {
                    b.HasOne("HybridWash.Entities.Models.Booking", "Booking")
                        .WithOne("ParkingReceipt")
                        .HasForeignKey("HybridWash.Entities.Models.ParkingReceipt", "BookingId")
                        .IsRequired()
                        .HasConstraintName("FK__ParkingRe__Booki__04E4BC85");

                    b.HasOne("HybridWash.Entities.Models.Staff", "IssueStaff")
                        .WithMany("ParkingReceiptIssueStaffs")
                        .HasForeignKey("IssueStaffId")
                        .IsRequired()
                        .HasConstraintName("FK__ParkingRe__Issue__05D8E0BE");

                    b.HasOne("HybridWash.Entities.Models.Staff", "VerifyStaff")
                        .WithMany("ParkingReceiptVerifyStaffs")
                        .HasForeignKey("VerifyStaffId")
                        .HasConstraintName("FK__ParkingRe__Verif__06CD04F7");

                    b.Navigation("Booking");

                    b.Navigation("IssueStaff");

                    b.Navigation("VerifyStaff");
                });

            modelBuilder.Entity("HybridWash.Entities.Models.PointLedger", b =>
                {
                    b.HasOne("HybridWash.Entities.Models.Booking", "Booking")
                        .WithMany("PointLedgers")
                        .HasForeignKey("BookingId")
                        .HasConstraintName("FK__PointLedg__Booki__68487DD7");

                    b.HasOne("HybridWash.Entities.Models.Customer", "Customer")
                        .WithMany("PointLedgers")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK__PointLedg__Custo__6754599E");

                    b.HasOne("HybridWash.Entities.Models.RewardRedemption", "RewardRedemption")
                        .WithOne("PointLedger")
                        .HasForeignKey("HybridWash.Entities.Models.PointLedger", "RewardRedemptionId")
                        .HasConstraintName("FK_PointLedger_RewardRedemptions");

                    b.Navigation("Booking");

                    b.Navigation("Customer");

                    b.Navigation("RewardRedemption");
                });

            modelBuilder.Entity("HybridWash.Entities.Models.Promotion", b =>
                {
                    b.HasOne("HybridWash.Entities.Models.Service", "Service")
                        .WithMany("Promotions")
                        .HasForeignKey("ServiceId")
                        .HasConstraintName("FK_Promotions_Services");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("HybridWash.Entities.Models.Reward", b =>
                {
                    b.HasOne("HybridWash.Entities.Models.Service", "Service")
                        .WithMany("Rewards")
                        .HasForeignKey("ServiceId")
                        .HasConstraintName("FK_Rewards_Services");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("HybridWash.Entities.Models.RewardRedemption", b =>
                {
                    b.HasOne("HybridWash.Entities.Models.Booking", "Booking")
                        .WithMany("RewardRedemptions")
                        .HasForeignKey("BookingId")
                        .HasConstraintName("FK_RewardRedemptions_Bookings");

                    b.HasOne("HybridWash.Entities.Models.Customer", "Customer")
                        .WithMany("RewardRedemptions")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK_RewardRedemptions_Customers");

                    b.HasOne("HybridWash.Entities.Models.Reward", "Reward")
                        .WithMany("RewardRedemptions")
                        .HasForeignKey("RewardId")
                        .IsRequired()
                        .HasConstraintName("FK_RewardRedemptions_Rewards");

                    b.Navigation("Booking");

                    b.Navigation("Customer");

                    b.Navigation("Reward");
                });

            modelBuilder.Entity("HybridWash.Entities.Models.Vehicle", b =>
                {
                    b.HasOne("HybridWash.Entities.Models.Customer", "Customer")
                        .WithMany("Vehicles")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK__Vehicles__Custom__412EB0B6");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("HybridWash.Entities.Models.Booking", b =>
                {
                    b.Navigation("BookingAddOns");

                    b.Navigation("ParkingReceipt");

                    b.Navigation("PointLedgers");

                    b.Navigation("RewardRedemptions");
                });

            modelBuilder.Entity("HybridWash.Entities.Models.Customer", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("PointLedgers");

                    b.Navigation("RewardRedemptions");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("HybridWash.Entities.Models.Promotion", b =>
                {
                    b.Navigation("BookingAddOns");

                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("HybridWash.Entities.Models.Reward", b =>
                {
                    b.Navigation("RewardRedemptions");
                });

            modelBuilder.Entity("HybridWash.Entities.Models.RewardRedemption", b =>
                {
                    b.Navigation("BookingAddOn");

                    b.Navigation("PointLedger");
                });

            modelBuilder.Entity("HybridWash.Entities.Models.Service", b =>
                {
                    b.Navigation("BookingAddOns");

                    b.Navigation("Bookings");

                    b.Navigation("Promotions");

                    b.Navigation("Rewards");
                });

            modelBuilder.Entity("HybridWash.Entities.Models.Staff", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("ParkingReceiptIssueStaffs");

                    b.Navigation("ParkingReceiptVerifyStaffs");
                });

            modelBuilder.Entity("HybridWash.Entities.Models.TimeSlot", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("HybridWash.Entities.Models.Vehicle", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
